# Generated by Django 4.2.11 on 2024-04-15 00:00

from django.db import migrations, models
import pulse_ai.therapist_session.validators


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistsession',
            name='session_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transcribed', 'Transcribed'), ('done', 'Done')], default='pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='therapistsession',
            name='session_audio',
            field=models.FileField(upload_to='sessions/', validators=[pulse_ai.therapist_session.validators.validate_audio_mime_type]),
        ),
    ]
