# Generated by Django 4.2.11 on 2024-04-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_session', '0003_remove_therapistsession_session_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='transcription',
        ),
        migrations.AddField(
            model_name='error',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='therapist_session.therapistsession'),
            preserve_default=False,
        ),
    ]
