# Generated by Django 4.2.11 on 2024-04-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_session', '0004_remove_error_transcription_error_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='transcription',
        ),
        migrations.AddField(
            model_name='summary',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='therapist_session.therapistsession'),
            preserve_default=False,
        ),
    ]
