# Generated by Django 4.2.11 on 2024-04-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_session', '0005_remove_summary_transcription_summary_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='modified_at',
        ),
    ]
