# Generated by Django 4.2.11 on 2024-04-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_session', '0006_remove_summary_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='therapist_session.therapistsession'),
        ),
    ]
