# Generated by Django 4.2.11 on 2024-04-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_session', '0007_alter_transcription_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='summary_text_file_url',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='transcription_text_file_url',
        ),
        migrations.AddField(
            model_name='summary',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_text_file',
            field=models.FileField(blank=True, null=True, upload_to='summaries/'),
        ),
        migrations.AddField(
            model_name='transcription',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='transcription_text_file',
            field=models.FileField(blank=True, null=True, upload_to='transcriptions/'),
        ),
    ]
