# Generated by Django 4.2.11 on 2024-04-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_session', '0008_remove_summary_summary_text_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
