# Generated by Django 4.2.11 on 2024-05-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist_session", "0009_therapistsession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistsession",
            name="session_audio",
            field=models.FileField(upload_to="sessions/"),
        ),
    ]
