# Generated by Django 4.2.11 on 2024-08-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("therapist_session", "0010_alter_therapistsession_session_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistsession",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="patients.patient",
            ),
        ),
    ]
