# Generated by Django 4.2.11 on 2024-08-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist_session", "0011_therapistsession_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistsession",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="therapistsession",
            name="session_name",
            field=models.CharField(max_length=50),
        ),
    ]
