# Generated by Django 4.2.11 on 2024-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist_session", "0012_therapistsession_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistsession",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
