# Generated by Django 4.2.11 on 2024-08-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_patient_therapist"),
        ("therapist_session", "0013_alter_therapistsession_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistsession",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="patients.patient",
            ),
            preserve_default=False,
        ),
    ]
