# Generated by Django 4.2.11 on 2024-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist_session", "0014_alter_therapistsession_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistsession",
            name="summary_regeneration_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="therapistsession",
            name="transcription_regeneration_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
