# Generated by Django 4.2.11 on 2024-08-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "therapist_session",
            "0015_therapistsession_summary_regeneration_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistsession",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
