# Generated by Django 4.2.11 on 2024-05-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
