# Generated by Django 4.2.11 on 2024-05-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_code_sent_at_user_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_auth",
            field=models.BooleanField(default=False),
        ),
    ]
