name: Pulse AI Deployement

on:
  push:
    branches: [ pulse_ai ]
  pull_request:
    branches: [ pulse_ai ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/pulse_ai' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          set -x
          echo "Starting deployment..."
          cd /home/ubuntu/patient-note-app || exit
          echo "Pulled latest code from git..."
          git pull
          echo "Installing dependencies..."
          pip install -r requirements.txt
          echo "Migrating the database..."
          python manage.py migrate
          echo "Restarting Gunicorn service..."
          sudo systemctl restart gunicorn
          echo "Reloading systemd daemon..."
          sudo systemctl daemon-reload
          echo "Deployment completed successfully."
